name: "dpt_fundamentals"
version: "1.0.0"
config-version: 2

profile: "default"

vars:
  target_db: GLUEDB
  target_schema: PUBLIC
  stage_name: GLUEDB.PUBLIC.GLUE_S3_STAGE
  wrk_schema: BRONZE
  file_format_json: MYDB.BRONZE.CSV_FORMAT
  purge_status: FALSE
  rawhist_db: MYDB

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dpt_fundamentals:
    dbt_training:
      +database: ANALYTICS
      staging:
        +materialized: view
      marts:
        +materialized: table

    glue_project:
      +database: GLUEDB
      raw:
        +materialized: table
        +schema: raw
      transform:
        +materialized: table
        +schema: transform
      mart:
        +materialized: table
        +schema: mart

    walmart:
      +database: walmart_analytics
      staging:
        +materialized: view
        +schema: staging
      marts:
        +materialized: table
        +schema: marts