version: 2

models:
  - name: walmart_store_dim
    columns:
      - name: store_id
        tests:
          - unique
          - not_null

  - name: walmart_date_dim
    columns:
      - name: date_key
        tests:
          - unique
          - not_null
      - name: full_date
        tests:
          - not_null

  - name: walmart_fact_table
    columns:
      - name: store_id
        tests:
          - not_null
      - name: weekly_sales
        tests:
          - not_null